version: '3.8'
services:
  backend:
    container_name: backend
    image: node:18
    volumes:
      - .:/workdir
    working_dir: /workdir
    ports:
      - 3000:3000
    command: >
      bash -c "
        npm run dev
      "
    tty: true
    stdin_open: true
